// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

function resolveDatasourceUrl(): string {
  const url = process.env["LOCAL_DATABASE_URL"] ?? process.env["DATABASE_URL"];
  if (!url || url.startsWith("libsql://")) {
    return "file:./dev.db";
  }
  return url;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: resolveDatasourceUrl(),
  },
});
